# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  lint:
    name: "Static code analysis"
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
        
    - uses: subosito/flutter-action@v1
    
    # Check for any formatting issues in the code.
    - name: Format
      run: flutter format --set-exit-if-changed .
    
    # Statically analyze the Dart code for any errors.
    - name: Analyze
      run: flutter analyze .
